# What do want?
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc # mongodb definition point to this pvc
spec:
  storageClassName: mylocalstorage
  accessModes:
    - ReadWriteOnce #mendatory field describing only one pod would access the storage at time
  resources:
    requests:
      storage: 1Gi # we want 1GigaByte storage
---
# How do we want it implemented. This section describe how storage resource would be reserved in cloud or any other physical hard drive
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage
spec:
  storageClassName: mylocalstorage
  capacity:
    storage: 1Gi # 1GigaByte storage space would be reserved
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/bhanuchaddha/Documents/mogodb"
    type: DirectoryOrCreate