apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: webapp # this decide the name of the pods created
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp # required to observe the pod
  template: # template of the pod
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5