# What do want?
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc # mongodb definition point to this pvc
spec:
  storageClassName: cloud-ssd # should match with StorageClass name
  accessModes:
    - ReadWriteOnce #mendatory field describing only one pod would access the storage at time
  resources:
    requests:
      storage: 2Gi # we want 2GigaByte storage
---
# How do we want it implemented. This section describe how storage resource would be reserved in cloud or any other physical hard drive
# We dont need to reserve the specific size here as storage is provisioned as per the request from PersistentVolumeClaim
apiVersion: storage.k8s.io/v1
kind: StorageClass # After being executed it become the PersistentVolume
metadata:
  name: cloud-ssd
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2 # type of storage. this is general usage ssd drive